// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycrpbclttismbkgmrtsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcnBiY2x0dGlzbWJrZ21ydHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDA1OTIsImV4cCI6MjA3NDMxNjU5Mn0.pti1Mxy-dtutiC5JzExv4tILuxnaVRvs8OB8dGVkGfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});